
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diana Paola
 */
public class GUICliente extends javax.swing.JFrame {
    
    Board boardShips = new Board();
    Board boardOponent = new Board(); 
    
    Cliente cliente = new Cliente();
    
    /**
     * Creates new form GUICliente
     */
    public GUICliente() {
        cliente.createConecction();
        cliente.createStreams();
        initComponents();
        setBoards();
    }
    
    public void setTableroContrincante(int tablero[][]){
        boardOponent.tablero = tablero;
    }
    public void setBoards(){
        boardOponent.setMatrix(jPanelOpponent);
        boardShips.setMatrix(jPanelShips);
        setX(jPanelCoordinatesXship);
        setX(jPanelCoordinatesXopponent);
        setY(jPanelCoordinatesYship);
        setY(jPanelCoordinatesYopponent);
    }
    
    public void setX(JPanel coordX){
        int w = coordX.getWidth() / 10;
        int h = coordX.getHeight() / 10;
        int space = 0;
        for(int i=0; i<10; i++){
            JLabel coordinatesX = new JLabel("" + i + "");
            coordinatesX.setBounds(i*w+w/2-2, 0, coordX.getWidth(), coordX.getHeight());
            
            coordX.add(coordinatesX);
            coordX.updateUI();
        }
    }
    
    public void setY(JPanel coordX){
        int w = coordX.getWidth() / 10;
        int h = coordX.getHeight() / 10;
        
        JLabel jArrayLabel[][];
        jArrayLabel = new JLabel[10][10];
        for(int i=0; i<10; i++){
            for(int j=0; j<10; j++){
                jArrayLabel[i][j] = new JLabel("" + i + "");
                jArrayLabel[i][j].setBounds(j*w, i*h, coordX.getWidth(), coordX.getWidth());
                coordX.add(jArrayLabel[i][j]);
                coordX.updateUI();
                break;
            }
        }        
    }
    
    public void adivinarCoordenadas() throws ClassNotFoundException{
        JFrame f=new JFrame();  
        int x = Integer.parseInt( JOptionPane.showInputDialog(f,"Coordenada X") );
        int y = Integer.parseInt( JOptionPane.showInputDialog(f,"Coordenada Y") );
        cliente.setAdivinaCoordenadas(x, y);
        try {
            cliente.sendServerAdivinaCoordenadas();
            //cliente.getRespuestaServidor();
        } catch (IOException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOpponent = new javax.swing.JPanel();
        jPanelShips = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPutShips = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelCoordinatesXopponent = new javax.swing.JPanel();
        jPanelCoordinatesXship = new javax.swing.JPanel();
        jPanelCoordinatesYship = new javax.swing.JPanel();
        jPanelCoordinatesYopponent = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jButtonSendCoordinates = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelOpponent.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanelOpponentLayout = new javax.swing.GroupLayout(jPanelOpponent);
        jPanelOpponent.setLayout(jPanelOpponentLayout);
        jPanelOpponentLayout.setHorizontalGroup(
            jPanelOpponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelOpponentLayout.setVerticalGroup(
            jPanelOpponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelShips.setBackground(new java.awt.Color(0, 102, 153));
        jPanelShips.setForeground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanelShipsLayout = new javax.swing.GroupLayout(jPanelShips);
        jPanelShips.setLayout(jPanelShipsLayout);
        jPanelShipsLayout.setHorizontalGroup(
            jPanelShipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelShipsLayout.setVerticalGroup(
            jPanelShipsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 16)); // NOI18N
        jLabel1.setText("Batalla naval");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Mi tablero");

        jButtonPutShips.setText("Poner barquitos");
        jButtonPutShips.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPutShipsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Coordenadas oponente");

        javax.swing.GroupLayout jPanelCoordinatesXopponentLayout = new javax.swing.GroupLayout(jPanelCoordinatesXopponent);
        jPanelCoordinatesXopponent.setLayout(jPanelCoordinatesXopponentLayout);
        jPanelCoordinatesXopponentLayout.setHorizontalGroup(
            jPanelCoordinatesXopponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanelCoordinatesXopponentLayout.setVerticalGroup(
            jPanelCoordinatesXopponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCoordinatesXshipLayout = new javax.swing.GroupLayout(jPanelCoordinatesXship);
        jPanelCoordinatesXship.setLayout(jPanelCoordinatesXshipLayout);
        jPanelCoordinatesXshipLayout.setHorizontalGroup(
            jPanelCoordinatesXshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        jPanelCoordinatesXshipLayout.setVerticalGroup(
            jPanelCoordinatesXshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCoordinatesYshipLayout = new javax.swing.GroupLayout(jPanelCoordinatesYship);
        jPanelCoordinatesYship.setLayout(jPanelCoordinatesYshipLayout);
        jPanelCoordinatesYshipLayout.setHorizontalGroup(
            jPanelCoordinatesYshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanelCoordinatesYshipLayout.setVerticalGroup(
            jPanelCoordinatesYshipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCoordinatesYopponentLayout = new javax.swing.GroupLayout(jPanelCoordinatesYopponent);
        jPanelCoordinatesYopponent.setLayout(jPanelCoordinatesYopponentLayout);
        jPanelCoordinatesYopponentLayout.setHorizontalGroup(
            jPanelCoordinatesYopponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanelCoordinatesYopponentLayout.setVerticalGroup(
            jPanelCoordinatesYopponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jButtonStart.setText("Iniciar juego");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonSendCoordinates.setText("Adivinar coordenadas");
        jButtonSendCoordinates.setEnabled(false);
        jButtonSendCoordinates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendCoordinatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButtonPutShips))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelCoordinatesYship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCoordinatesXship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelShips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCoordinatesYopponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelCoordinatesXopponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOpponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButtonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSendCoordinates)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonPutShips)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCoordinatesXship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelShips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCoordinatesYship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCoordinatesYopponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelOpponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelCoordinatesXopponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonSendCoordinates))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPutShipsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPutShipsActionPerformed
       this.boardShips.ColocarBarcos();
       JButton boton = (JButton)evt.getSource();
       boton.setEnabled(false);
       JFrame f=new JFrame();
       String nombre = JOptionPane.showInputDialog(f,"Nombre de jugador");
       cliente.Negociar(nombre);
       this.jButtonSendCoordinates.setEnabled(true);
    }//GEN-LAST:event_jButtonPutShipsActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
            
        try{
            List<Coordenadas> listCoo= new ArrayList<>(); 
            listCoo = boardShips.getlistCoordClient();
            
            Coordenadas inicio = new Coordenadas(boardShips.tablero, boardShips.getlistCoordClient());
            List<Coordenadas> listCoo2= new ArrayList<>(); 
            
            cliente.sendPacket(inicio);
            jButtonPutShips.setEnabled(false);
            ((JButton)(evt.getSource())).setEnabled(false);
            Coordenadas c = (Coordenadas)cliente.recivePacket();
            cliente.Jugar(c.whoInit,c.tablero, this);
        }catch(Exception e){
            e.printStackTrace();
        }
        
            
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonSendCoordinatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendCoordinatesActionPerformed
        try {
            adivinarCoordenadas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSendCoordinatesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPutShips;
    private javax.swing.JButton jButtonSendCoordinates;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelCoordinatesXopponent;
    private javax.swing.JPanel jPanelCoordinatesXship;
    private javax.swing.JPanel jPanelCoordinatesYopponent;
    private javax.swing.JPanel jPanelCoordinatesYship;
    private javax.swing.JPanel jPanelOpponent;
    private javax.swing.JPanel jPanelShips;
    // End of variables declaration//GEN-END:variables
}
